### ISSUE TITLE
Mapping drug-target to disease by ICD 10 or 11

### ISSUE THREAD

**Issue by anbai106** [dhimmel/drugbank#9]
Hi team,
I want to ask how we can map the extracted information from DrugBank to ICD-10 or 11. In the Therapeutic Target Database, they provide this kind of mapping. Sorry if I asked a very naive question -- recently stepped into this exciting field!

Thanks

**Comment by dhimmel** [comment]
I think this question comes down to how to map DrugBank diseases to ICD10 or ICD11. This repo does not work with any disease information from DrugBank, so I am going to close this as not planned.
